apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-volv-pvc
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
